# Gitlab ci/cd file configuration

default:
  image: "maven:3-openjdk-8"

before_script:
  - export PATH=$PATH:"$CI_PROJECT_PATH/global/bin"
  - export PATH=$PATH:"$CI_PROJECT_PATH/src/main/bin"
  - export PATH=$PATH:"$CI_PROJECT_PATH/src/test/script"
  - export PATH=$PATH:"$CI_PROJECT_PATH/src/test/script/launchers"

stages:
  - clean
  - compile
  - test
  - deploy


clean:
  stage: clean
  script:
    - mvn clean

compile:
  stage: compile
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

deploy:
  stage: deploy
  script:
    - mvn deploy
