# Gitlab ci/cd file configuration

default:
  image: "maven:3-openjdk-8"

before_script:
  - export PATH=$PATH:"$CI_PROJECT_DIR/global/bin"
  - export PATH=$PATH:"$CI_PROJECT_DIR/src/main/bin"
  - export PATH=$PATH:"$CI_PROJECT_DIR/src/test/script"
  - export PATH=$PATH:"$CI_PROJECT_DIR/src/test/script/launchers"

stages:
  - clean
  - compile
  - simple-test
  - complete-test
  - deploy


clean:
  stage: clean
  script:
    - mvn clean

compile:
  stage: compile
  script:
    - mvn compile

simple-test:
  stage: simple-test
  script:
    - mvn test

complete-test:
  stage: complete-test
  script:
    - mvn test -DskipSystemTests=false

deploy:
  stage: deploy
  script:
    - mvn deploy
